---
info:
  title: Rex Arch
  description: Rex Library which contains architecture specific information such as
    registers, opcodes, and stack manipulation routines.
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/rex-arch
  x-cortex-tag: rex-arch
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
